### ISSUE TITLE
Make description in english?

### ISSUE THREAD

**Issue by FrameMuse** [LeeMir/react-time-bar#10]
I think this would be nice if there was _readable_ description.

**Comment by LeeMir** [comment]
@FrameMuse 

Thank you for suggestion. 😃
I agree with you, so I'll try it *ASAP* 🔥

**Comment by FrameMuse** [comment]
[ASAP](https://www.youtube.com/watch?v=NsY-9MCOIAQ)?

**Comment by LeeMir** [comment]
*As Soon As Possible* 😆

**Comment by FrameMuse** [comment]
https://github.com/LeeMir/react-holiday-time-bar/blob/main/README-EN.md
